version: '3'
services:
  game:
    container_name: orion-game
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    depends_on:
      - login
    ports:
      - "8585:8585"
      - "8686:8686"
    environment:
      - MAIN_CLASS=game.GameApp
      - SERVICE_OPTS="-DgameID=0 -Dwzpath=data/"
    volumes:
      - ../data:/opt/server/data
      - ../sql:/opt/server/sql

  login:
    container_name: orion-login
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8484:8484"
    environment:
      - MAIN_CLASS=login.LoginApp
      - SERVICE_OPTS="-Dwzpath=data/"
    volumes:
      - ../data:/opt/server/data
      - ../sql:/opt/server/sql

  shop:
    container_name: orion-shop
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    depends_on:
      - game
    ports:
      - "8787:8787"
      - "8888:8888"
    environment:
      - MAIN_CLASS=shop.ShopApp
      - SERVICE_OPTS="-Dwzpath=data/"
    volumes:
      - ../data:/opt/server/data
      - ../sql:/opt/server/sql

  db:
    container_name: orion-db
    image: mariadb:latest
    volumes:
      - ./docker-db-data:/var/lib/mysql
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orionalpha
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "3306:3306"
